### ISSUE TITLE
Lying about the modified date for a Timestamped model is difficult.

### ISSUE THREAD

**Issue by kezabelle** [jazzband/django-model-utils#109]
A bit of prelude: 
Sometimes it is useful to be able to lie to the database about when things happened. Mostly this kind of thing is useful when copying/cloning existing objects (or their attributes to another instance).
Django doesn't make this easy with it's `auto_now`/`auto_now_add` attributes for date based fields, as they always take precedence:

```
class MyModel(Model):
    created = DateTimeField(auto_now_add=True)
    modified = DateTimeField(auto_now=True)
```

It is impossible to lie to the database efficiently:

```
old = datetime.now() - timedelta(days=365)
obj, created = MyModel.objects.create(created=old, modified=old)
# the inserted object won't have the value held in `old`
obj.created = old
obj.save() 
# now it will.
```

So that rules Django's builtin timestamping out.
In model utils, we have `TimestampedModel` which itself is just a collection of the two Auto fields; using this model we can get slightly further in our lying:

```
class MyModel2(TimestampedModel): pass
```

now we can lie efficiently about our creation time:

```
old = datetime.now() - timedelta(days=365)
obj, created = MyModel2.objects.create(created=old, modified=old)
# the inserted object will have the `old` value for created, but not modified.
```

but not our `modified` time, which doesn't test the model instance for the attr's existance before applying it's own.

Personally, I'd be keen to have the lying be possible, but it would be technically backwards incompatible to do so: users might be supplying a modified date and relying on it _not_ being applied (perhaps by having a blanket set of **kwargs and not popping `modified` out)

As there are no tests I can see demonstrating a preferred intention, I'm opening this for discussion on whether there's merit to perhaps allowing this.

**Comment by andreoliwa** [comment]
I think this issue was fixed in https://github.com/jazzband/django-model-utils/pull/388 with this commit: https://github.com/jazzband/django-model-utils/commit/cfbea2ca89c0262a0576c926d5c525bd3315c6b5
