### ISSUE TITLE
FieldTracker documentation should mention that by default ForeignKeys are tracked by db_column instead of field name

### ISSUE THREAD

**Issue by imposeren** [jazzband/django-model-utils#195]
When field tracker is initialized without specifying fields then it tracks ForeignKey fields by db_column name. But when initialized with fields specified then FK fields may be tracked by field name

``` python
class Foo(models.Model):
    bar = models.ForeignKey('bar')
    baz = models.CharField(max_length=5)

    simple_tracker = FieldTracker()
    specific_tracker = FieldTracker(fields=['bar', 'baz'])

```

``` python
>>> foo = Foo()
>>> foo.simple_tracker.fields
set(['bar_id' ,'baz''])
>>> foo.specific_tracker.fields
set(['bar' ,'baz''])
```

And documentation should also mention that using field name instead of db_column is bad idea: if foreign key is tracked by name and this field deferred then model initialization will fail. Or maybe this should be fixed as an issue.

```
>>> foo = Foo.objects.all().first()
>>> foo.pk
1
>>> foo = Foo.objects.all().only('baz').first()
...
File ".../model_utils/tracker.py", line 78, in __get__
    instance._deferred_fields.remove(field.field_name)
ValueError: list.remove(x): x not in list
```

**Comment by carljm** [comment]
Thanks for the report. Pull requests welcome for any or all of the above.
