### ISSUE TITLE
Use "Python identifier" from three-tuple Choices in StatusModel

### ISSUE THREAD

**Issue by chronossc** [jazzband/django-model-utils#25]
Hello Carl.

I started to use StatusModel this week (amazing tool btw) and with model like that:

```
class MyModel(StatusModel):
    STATUS = Choices(
        ('0', 'nao_atendido', 'Não atendido'),
        ('10', 'em_atendimento', 'Em atendimento'),
        ('11', 'contato_sem_sucesso', 'Contato sem sucesso'),
        ('20', 'atendido_sem_sucesso', 'Atendido sem sucesso'),
        ('21', 'atendido_com_sucesso', 'Atendido com sucesso')
    )
```

If I do:

```
>>> x = MyModel(status=MyModel.STATUS.nao_atendido)
>>> x.status
u'0'
>>> x.0
x.0
  ^
SyntaxError: invalid syntax
```

Same happens with a saved instance.

So, IMO, in case of tree tuple choice, it should use second item instead first item to create managers, and, _never_ use a digit.

I love to write patches for you, but since I'm not needing this feature right now and without time I just created that issue.

**Comment by merwok** [comment]
To complement Carl’s answer:

This is regular Python behaviour, attribute access must follow the rules for identifier (e.g. `Delay.time3h` is valid code but not `Delay.3h`).  The work around is to use `getattr(Delay, "3h")`.
