### ISSUE TITLE
SoftDeletableModel - show deleted in Django admin

### ISSUE THREAD

**Issue by volkandkaya** [jazzband/django-model-utils#255]
It would be nice to have deleted fields show up in the Django admin panel. I have tried to implement it but the hard coded filter has stopped me.

**Comment by romgar** [comment]
Hi @volkandkaya ! How would you imagine them to show up?

**Comment by volkandkaya** [comment]
@romgar Maybe a tick box at the top. However I don't know how hard it is to customise Django admin panel. Quickest way I guess would be to pass a variable into filter or create a custom method, that way you can use get_queryset in admin.ModelAdmin.

**Comment by Nixsm** [comment]
How about adding `all_objects` in the SoftDeletableModel and then you would customize your Django admin accordingly

**Comment by natecox** [comment]
Is there any traction on this? Being able to "undelete" from the admin would be a huge boon, even if it just means providing a second manager with all objects and overriding the queryset on the admin.

**Comment by marcorichetta** [comment]
Should this be closed? As the proposed solution has already been merged. @auvipy
