### ISSUE TITLE
Customising model_ptr name

### ISSUE THREAD

**Issue by tyteen4a03** [jazzband/django-model-utils#263]
Is it possible to customise the column name of the submodel pointer (currently `modelclassname_ptr`) generated by InheritanceManager?

**Comment by kezabelle** [comment]
I believe the feature you're describing wanting to change is actually one of Django itself, and for your purposes you would need to [specify the parent link field](https://docs.djangoproject.com/en/stable/topics/db/models/#specifying-the-parent-link-field). 

You can see an example in the `django-model-utils` [test models](https://github.com/carljm/django-model-utils/blob/master/model_utils/tests/models.py#L68), and that it is [already tested and supported](https://github.com/carljm/django-model-utils/blob/master/model_utils/tests/test_managers/test_inheritance_manager.py) once you've made the change.
