### ISSUE TITLE
Drop 1.10 and below?

### ISSUE THREAD

**Issue by tony** [jazzband/django-model-utils#296]
source: https://docs.djangoproject.com/en/2.0/releases/2.0/

> Following the release of Django 2.0, we suggest that third-party app authors drop support for all versions of Django prior to 1.11. At that time, you should be able to run your package’s tests using python -Wd so that deprecation warnings do appear. After making the deprecation warning fixes, your app should be compatible with Django 2.0.

Backstory is Django 1.11 is LTS (Supported until April 2020).

**Comment by richardbarran** [comment]
Closing this issue as django-model-utils is no longer tested against Django < 1.11.
