### ISSUE TITLE
3.1.0 unavailable on PyPI.

### ISSUE THREAD

**Issue by digismack** [jazzband/django-model-utils#304]
## Problem

3.1.0 unavailable on PyPI.

## Environment

n/a

## Code examples

n/a

**Comment by tony** [comment]
See: https://github.com/jazzband/roadies/issues/79

I don't think I have authorization to publish to pypi. @jezdez Anything else that needs to get setup to get 3.1.0 published?

**Comment by pwhipp** [comment]
3.1.1 now. This is essential for Django 2 upgrade.

**Comment by inureyes** [comment]
Please check pypi package. It is still 3.0.0 therefore I had to install from GitHub.

<img width="1293" alt="screen shot 2018-01-08 at 4 05 35 pm" src="https://user-images.githubusercontent.com/949915/34661556-df1baba2-f48d-11e7-90df-c34ea287a78c.png">

**Comment by digismack** [comment]
Looks like this is no longer a problem.
