### ISSUE TITLE
README.rst stats incorrect compatibility information?

### ISSUE THREAD

**Issue by adrianboyko** [jazzband/django-model-utils#305]
## Problem

README says "django-model-utils supports Django 1.8 through 1.10 (latest bugfix release in each series only) on Python 2.7, 3.3 (Django 1.8 only), 3.4 and 3.5."  However, the release notes seem to say that support for Django 1.11 was added in DMU 3.0.0.

## Environment

n/a

## Code examples

n/a

**Comment by tony** [comment]
You can submit a PR, or I'll fix it in the AM tomorrow, a bit too tired to avoid mistakes now.
