### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured

### ISSUE THREAD

**Issue by Germano0** [jazzband/django-model-utils#311]
## Problem
I was updating django-model-utils on Fedora to the 3.1.1 version, when I got the following error

> django.core.exceptions.ImproperlyConfigured: Requested setting SPLIT_MARKER, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.

in https://kojipkgs.fedoraproject.org//work/tasks/1700/24281700/build.log

## Environment

- Django Model Utils version: 3.1.1
- Django version: python-django-1.11.9-2.fc28
- Python version: python3-3.6.4-4.fc28 python2-2.7.14-7.fc28

**Comment by encukou** [comment]
I can reproduce in a python3 venv with 1.11.9, after running:

    python setup.py test
