### ISSUE TITLE
AttributeError: Can't pickle local object 'FieldTracker.patch_save.<locals>.save'

### ISSUE THREAD

**Issue by GianmarSanchez** [jazzband/django-model-utils#330]
## Pickle a model instance for django cache

In the tests that use cache, this error does not allow to serialize the instances that have an attribute with FieldTracker

## Environment

- Django Model Utils version: django-model-utils-3.1.2
- Django version: Django==2.0.7
- Python version: 3.6.5

## Output
`File "/home/xxxxx/xxxxx/xxxxx/xxxxx/tracker/models.py", line 486, in load_cache
    cache.set(self.user_id, self)
  File "/home/xxxxx/xxxxx/xxxxx/env/lib/python3.6/site-packages/django/core/cache/backends/locmem.py", line 69, in set
    pickled = pickle.dumps(value, pickle.HIGHEST_PROTOCOL)
AttributeError: Can't pickle local object 'FieldTracker.patch_save.<locals>.save'
`

**Comment by coler-j** [comment]
What is the pypy release cycle like? I install v3.1.2 this fix is not present.
