### ISSUE TITLE
Allow FieldTracker on Django user model (and other children of abstract base classes)

### ISSUE THREAD

**Issue by jcushman** [jazzband/django-model-utils#331]
## Problem

Here is a branch with failing tests that I think should work (and that I think worked in earlier versions?): https://github.com/jazzband/django-model-utils/compare/master...jcushman:abstract-test-failure

This seems to be related to the stuff that @lucaswiman added in #317. @lucaswiman, I'm hoping based on that work you might have some clever idea for how to fix this. :)

Here's the situation: you have an abstract base class that defines a static attribute like `is_active = True`, and a concrete model inheriting from that class that defines a field like `is_active = models.BooleanField(default=True)`. The model then throws an error on `save()`:

```
from django.contrib.auth.models import AbstractUser

class MyUser(AbstractUser):
    tracker = FieldTracker()

MyUser().save()
```

Result:

```
    def __get__(self, instance, owner):
        if instance is None:
            return self
        was_deferred = self.field_name in instance.get_deferred_fields()
>       value = self.descriptor.__get__(instance, owner)
E       AttributeError: 'bool' object has no attribute '__get__'

model_utils/tracker.py:43: AttributeError
```

It would be great for this to work, because tracking changes on the Django user model is handy.

Debugging that error, I found the problem boils down to this:

```
class AbstractUser(models.Model):
    is_active = True

    class Meta:
        abstract = True

class MyUser(AbstractUser):
    is_active = models.BooleanField(default=True)
    tracker = FieldTracker()

MyUser().save()
```

The reason that fails is https://github.com/jazzband/django-model-utils/blob/master/model_utils/tracker.py#L218 :

```
descriptor = getattr(sender, field_name)
...
setattr(sender, field_name, wrapped_descriptor)
```

... which boils down to setting `MyUser.is_active = DescriptorWrapper(MyUser.is_active)`. And _that_ doesn't work because you expect `MyUser.is_active` to start with a value of `DeferredAttribute('is_active')`, but it actually returns `True`. For reasons I don't understand, when you override a static attribute on an abstract class, you get the base class's value back instead of the subclass's.

I tried tweaking tracker.py with variations on `descriptor = getattr(sender, field_name) if field_name in sender.__dict__ else DeferredAttribute(field_name)`, but that broke foreign key fields and feels pretty janky anyway.

Any ideas on how to get this working?

Thanks!

## Environment

- Django Model Utils version: master
- Django version: 2.1
- Python version: 3.6
- Other libraries used, if any:

**Comment by lucaswiman** [comment]
The cause is here:
https://github.com/django/django/blob/2.1/django/db/models/fields/__init__.py#L740-L745

When setting up the `DeferredAttribute` descriptors, the case of the base class already having the attribute defined is explicitly unhandled, so deferring fields doesn't work in this case. I guess in this case, we would want to use some custom descriptor, though I'm guessing that would run into whatever problem caused Django to not support deferred fields in the first place. 

I'm not quite sure the right way to fix this, but hopefully that extra bit of information helps out. 🤔

**Comment by lucaswiman** [comment]
I think according to the comment in django source code I linked to above, deferring a field defined with a static value on a superclass is undefined behavior. So your test should only set `name`, not `number`, since the tests use `.only('name')` and hence defer `number. (The tests still fail after doing that.)

**Comment by slurms** [comment]
Will it work to just not wrap attributes that aren't descriptors? I ended up with something like:

```
descriptor = getattr(sender, field_name)
if isinstance(descriptor, DeferredAttribute):
    wrapper_cls = DescriptorWrapper.cls_for_descriptor(descriptor)
    wrapped_descriptor = wrapper_cls(field_name, descriptor, self.attname)
    setattr(sender, field_name, wrapped_descriptor)
```

And that seems to work on the codebase I'm running it on.

**Comment by maciekz** [comment]
I hope this issue can be handled as I'm experiencing it as well and with the same "is_active" field. The fix provided by @slurms does make the problem go away.

**Comment by aidanlister** [comment]
+1 for getting this fixed. We've put https://github.com/jazzband/django-model-utils/pull/336 into production and it seems to be fine.

**Comment by jarekwg** [comment]
+1
Anyone have a better idea than just checking if the descriptors are `DeferredAttribute`s?
@slurms why'd you end up closing your PR (if you remember)?
Did you find a better solution, or just lack of time to finish the PR?
We're currently relying on #336 in production heh. Would be nice to have this code (or some other solution) merged back into DMU...

**Comment by lucaswiman** [comment]
#336 looks like a reasonable solution to the problem if you want to take up fleshing out the tests.

**Comment by slurms** [comment]
@jarekwg I closed the PR because when I opened it it was causing test failures (so I thought I'd broken something). I never got around to fixing it simply because I'm lazy and figured someone would find the "right" way to do it :). I'll resurrect it and see if I can get tests passing and then hopefully we have something we can merge.

**Comment by slurms** [comment]
I think catching the `AttributeError` might be the better approach: https://github.com/jazzband/django-model-utils/pull/367

**Comment by jarekwg** [comment]
Awesome!
Thanks @slurms and @auvipy.
Lettuce know when a new release is published. :)

**Comment by jarekwg** [comment]
Hrm, looks like this new solution doesn't work for our use case. #336 did. I've added a monkeypatch directly into our codebase atm to include the #336 change.

Here's the use case:

We have a `User` class that subclasses `django.contrib.auth.models.AbstractBaseUser`.
This `User` class has some additional fields, one of which is a `BooleanField` `is_active`.
We have a `FieldTracker` set up to track some of the fields on this model, including `is_active`.
As it is now, attempting to set `is_active` on a `User` instance, does nothing:
```
>>> u = User.objects.first()
>>> u.is_active
True
>>> u.is_active = False
>>> u.is_active
True
```
Saving aside, the setter itself is stubbornly ignorant.

I'm happy to write a failing test and add a solution in another PR, if someone could give me a quick pointer as to how to run the test suite locally. I've tried `python setup.py test`, `tox` and `py.test` and all are falling over on db issues. Probs a silly question, but yeah, would be nice to have explicit instructions on how to run the tests.. Interestingly I've contributed to this repo before, so either I've forgotten how to run the tests, or something has changed.. -.-

Cheers,
Jarek

**Comment by jcushman** [comment]
@jarekwg, for getting the test suite running, check out https://github.com/jazzband/django-model-utils/blob/master/.travis.yml to figure out what your environment might be missing. I notice that it requires postgres, so it could be you need that locally? In any event copying and pasting the command from there (`tox -- --cov --cov-append`) worked for me, at least for the python versions I had installed.

**Comment by jcushman** [comment]
@slurms, @auvipy, just wanted to make sure you saw the comment by @jarekwg above -- the accepted PR creates a security bug for typical uses of `AbstractBaseUser`:

```
class User(AbstractBaseUser):
    is_active = models.BooleanField(default=True)
    tracker = FieldTracker()

In [1]: a=User.objects.first()
In [2]: a.is_active
Out[2]: True
In [3]: a.is_active=False
In [4]: a.save()
In [5]: a.is_active
Out[5]: True
```

In this example **adding FieldTracker to the model silently disables existing code to deactivate user accounts**.

Note for anyone who needs a workaround -- this simple monkeypatch seems to avoid the problem for now:

```
del AbstractBaseUser.is_active  # delete the shadowed attribute

class User(AbstractBaseUser):
    is_active = models.BooleanField(default=True)
    tracker = FieldTracker()
```

**Comment by jarekwg** [comment]
yep, thanks, finally had another look last week and got the test suite running (just needed to spin up local postgres as you say). Attempting to reinstate slurms' old solution (which we're currently using as a monkeypatch in production) broke several tests, so I'll write my test first, then will have another play when i have some spare time. Re your sample code above, can drop the `save()` line -- it makes no difference whether we attempt to save or not; the value should get set immediately.

**Comment by jcushman** [comment]
>Re your sample code above, can drop the save() line -- it makes no difference whether we attempt to save or not; the value should get set immediately.

Yeah, to be clear, I included `save()` to demonstrate that the current master branch is significantly more dangerous than before. Prior to #367, adding FieldTracker to `User` would cause a noisy error on save. It now (in typical usage) causes users to silently stay activated when they should be deactivated -- save working in that example is bad news!

**Comment by slurms** [comment]
Yup, apologies -- the PR was merged before I had the chance to write proper tests for it. @jarekwg how's that coming along, you get the tests running?

**Comment by jarekwg** [comment]
@slurms yeah got testsuite running; will raise pr with failing test (and hopefully a fix that doesn't break any other tests) soon^(TM).

**Comment by jarekwg** [comment]
So, after a solid dig,
#336 is not a sufficient fix (albeit it's what we've patched into production for the time being), because it doesn't handle nonstandard DeferredAttributes (such as custom Descriptors) properly.
#367 only masks the issue, by grabbing the underlying attribute from the base class instead of the value from the descriptor.
I'll push up a PR in a second, with a failing test, but I have a feeling that this is an issue in Django itself.
This code is no longer able to correctly grab the descriptor by accessing the field from the model:
https://github.com/jazzband/django-model-utils/blob/master/model_utils/tracker.py#L220-L225

As an example:
```
class Base(models.Model):
    A = 1


class Inherited(Base):
    A = models.IntegerField(default=0)
    B = models.IntegerField(default=0)
```
And now take a look at this:
```
>>> Inherited.A
1
>>> Inherited.B
<django.db.models.query_utils.DeferredAttribute object at 0x110ed5470>
```

This is without `abstract=True` on the base class; without setting a `FieldTracker` on the child class.
Looks to me like this is just plain wrong.

I'll raise this with the Django gods and get back with what they have to say.

**Comment by jcushman** [comment]
Nice work! Just a shot in the dark, but since inheritance does work for instances, could we get where we need to be by doing the wrapping per-instance in `initialize_tracker` instead?

**Comment by jarekwg** [comment]
We could certainly grab the value off the instance, before and after. But we rely on the wrapped descriptor to tell us when a change has occurred.
So we'd likely need a combination of both.. somehow.
Also, simply changing:
`value = self.descriptor.__get__(instance, owner)`
at https://github.com/jazzband/django-model-utils/blame/master/model_utils/tracker.py#L44
to `value = getattr(instance, self.field_name)`
is not sufficient, for reasons I didn't end up delving further into.

**Comment by mxschmitt** [comment]
The issue for me is still persistent in version `3.2.0`. :/
Same behavior with the `is_active` attribute like described above.

**Comment by dmugtasimov** [comment]
The reason for this issue is that `django.contrib.auth.models.AbstractBaseUser` has class level attribute `is_active`:
```
class AbstractBaseUser(models.Model):
    password = models.CharField(_('password'), max_length=128)
    last_login = models.DateTimeField(_('last login'), blank=True, null=True)

    is_active = True
```

```
(Pdb++) instance.is_active
True
(Pdb++) instance.is_active = False
(Pdb++) instance.is_active
True
```

After applying this work around it works just fine:
```
if hasattr(AbstractBaseUser, 'is_active'):
    del AbstractBaseUser.is_active
```


```
(Pdb++) instance.is_active
False
(Pdb++) instance.is_active = True
(Pdb++) instance.is_active
True
(Pdb++) instance.is_active = False
(Pdb++) instance.is_active
False
```

I think it deserves a fix either in django-model-utlils or in Django.

**Comment by jarekwg** [comment]
Yeahs, Django PR still awaiting final review: https://github.com/jazzband/django-model-utils/issues/331#issuecomment-488214663
They're pretty busy over there. :/
The #336 fix is the one I'm still currently using in production, and might suggest just releasing here until django addresses this properly.

**Comment by tell-k** [comment]
Hi. Is there any chance this problem can be fixed? I'm struggling with this issue now. I'm hoping it will be fixed.

**Comment by tumb1er** [comment]
Fix in django-model-utils depends on this pr: https://github.com/django/django/pull/11337#pullrequestreview-454009820
Looks like we may see it in Django-3.2.

**Comment by tell-k** [comment]
@tumb1er Thank you for sharing that with me. I'm looking forward to the release of Django 3.2. :)
