### ISSUE TITLE
Unfortunate behavior of `FieldTracker` around `refresh_from_db()`

### ISSUE THREAD

**Issue by dakotahawkins** [jazzband/django-model-utils#345]
## Problem

The behavior of a `FieldTracker` around changes to a model instance after a call to `refresh_from_db()` seems unexpected.

I encountered this in a unit test for a rest framework view where a user has permission to change a tracked field a certain way but not change it back (the change represents moving the instance from one group to another).

To reset the db when it's not possible using the view, I attempted to:
1. Call `save()` on my local instance to put back the old value
2. Call `refresh_from_db()`, set the field to its old value, and `save()`

I found out that both of those update the database as expected, but in both cases the tracked field thinks it hasn't changed, and so my `post_save` signal bails early instead of updating object permissions in response to the change.

I would expect that behavior in the first case above, since the local instance was never updated.

In the second case, however, I expected (maybe naively) that calling `refresh_from_db()` would re-set the tracked fields, allowing a subsequent manual setting of the field and `save()` to do what I wanted.

I found that it was necessary to call `save()` immediately after `refresh_from_db()` to get the tracker back on track.

## Environment

- Django Model Utils version: `3.1.2`
- Django version: `2.1.3`
- Python version: `3.7.0`
- Other libraries used, if any:

## Code examples

```python
"""Test models"""

from django.db import models
from model_utils import FieldTracker

class SimpleTrackedModel(models.Model):
    """Simple model with tracked name"""

    def __str__(self):
        return self.name

    name = models.CharField(max_length=50)
    tracker = FieldTracker(fields=['name'])
```

```python
"""Field tracker tests"""

from django.test import TestCase

from test_app.models import SimpleTrackedModel

class GenericTrackerTest(TestCase):
    """Test generic tracker"""

    def setUp(self):
        """Performs per-test initialization"""

        self.instance: SimpleTrackedModel = SimpleTrackedModel.objects.create(name='Old name')

    def test_refresh_from_db(self):
        """Test tracker after untracked update() and refresh_from_db()"""

        old_name = self.instance.name
        new_name = 'New name'

        # Call update(), nothing changed locally (as expected)
        updated: int = SimpleTrackedModel.objects.filter(pk=self.instance.pk).update(name=new_name)
        self.assertEqual(updated, 1)
        self.assertEqual(self.instance.name, old_name)
        self.assertDictEqual(self.instance.tracker.changed(), {})

        # refresh_from_db(), and now we have changes (even though save() won't change anything)
        self.instance.refresh_from_db()
        self.assertEqual(self.instance.name, new_name)
        self.assertDictEqual(self.instance.tracker.changed(), {'name': 'Old name'})

        # If we re-set the value, the tracker doesn't show changes even though this would be a change
        self.instance.name = old_name
        self.assertDictEqual(self.instance.tracker.changed(), {})

        # To get this to work, we have to refresh_from_db() and then save!
        self.instance.refresh_from_db()
        self.assertEqual(self.instance.name, new_name)
        self.instance.save()
        self.instance.name = old_name

        self.assertDictEqual(self.instance.tracker.changed(), {'name': 'New name'})
```

**Comment by dakotahawkins** [comment]
To clarify:

I think the semantics around `FieldTracker` are "show me things that my changes to tracked fields would change in the db if I `.save()`, if you can."

In some cases, like making a change with `.update()` in the example (or making a change through a view/request as in my original problem, or having the change happen behind your back from another user) are understandable -- nothing told my model instance to change its state.

In the case of a `.refresh_from_db()` I thought the tracker would/should update, clearing any existing changes. The model instance is updated, so an immediate `save()` afterwards should have no effect and it trivially (imo) shouldn't be necessary.

If we replace the `.refresh_from_db()` with a `instance = ...get(pk=instance.pk)`, that's what happens (of course, replace the instance get a blank slate for the tracker).

If this is either by design (possible) or necessary for a technical reason (maybe more possible), I think it would be nice to have this behavior explicitly documented, if only because it took me so long to figure out what was happening in the first place :)

**Comment by tumb1er** [comment]
See #403 -  looks like it fixes this issue.
