### ISSUE TITLE
When will changes in master be merged?

### ISSUE THREAD

**Issue by coler-j** [jazzband/django-model-utils#357]
I am waiting for https://github.com/jazzband/django-model-utils/issues/330 to be included in master as this presently breaks caching for my application.

Should use the unreleased version / master?

Should I fork and merge the change as a hotfix to current release?

**Comment by dnmellen** [comment]
I see travis builds are failing in master branch and this PR solves this problem: https://github.com/jazzband/django-model-utils/pull/358

**Comment by auvipy** [comment]
you can install from github master branch using pip.

**Comment by coler-j** [comment]
Well of course I can do that. But what other changes are in master? When are the changes in master going to be promoted to a new release? Is there an issue to track this?
