### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by illing2005** [jazzband/django-model-utils#366]
Is there a new release planned in near future? 3.1.2 is from May 2018 and master changed a lot since that

**Comment by snstanton** [comment]
We're running into issues because we can't use 'pip freeze' without end up with a back-rev'ed version.  Please cut a new release to pypi.

**Comment by rjschave** [comment]
@saadullahaleem, While we wait for a new release, have you considered pip installing to a specific commit version?

This will get you most recent version, 3.2 (as of this post):
```
pip install git+https://github.com/jazzband/django-model-utils.git@c4a252d1fb38c8fa7c645bc9292712e2fdf4d7c1#egg=django-model-utils
```

or drop this in your requirements.txt file:
```
-e git+https://github.com/jazzband/django-model-utils.git@c4a252d1fb38c8fa7c645bc9292712e2fdf4d7c1#egg=django-model-utils
```
Then just replace that line when the new release drops.

**Comment by Marik1234** [comment]
When we can expect new release?

**Comment by MRigal** [comment]
It's been one year now, without new release and enough bug fixes...

**Comment by cristeaadrian** [comment]
Would really appreciate a PyPI release, as the latest commits add Django 2.2 support which we need. Thanks 👍
