### ISSUE TITLE
Requirements Mismatch: 1.8 or 1.11?

### ISSUE THREAD

**Issue by DylanYoung** [jazzband/django-model-utils#375]
## Problem

Docs say v3.2.0 support Django 1.8+
setup.py says install_requires Django 1.11+

Which is it?

**Comment by DylanYoung** [comment]
Happy to leave a PR if you can confirm an answer.

**Comment by jonathan-s** [comment]
Considering that 1.11 is the current long term release I'd say it should be 1.11. Version 1.8 is deprecated from a django perspective.
