### ISSUE TITLE
FieldTracker cannot update boolean

### ISSUE THREAD

**Issue by brianmay** [jazzband/django-model-utils#391]
## Problem

I have the following field, in a Django model:

```
is_active = models.BooleanField(default=True)
...
_tracker = FieldTracker()
```

I try to change it to False:

```
self.is_active = False
assert self.is_active == False
```

Note I haven't tried calling `save()` yet. Under django-model-utils 3.1.2 it works. Under django-model-utils 3.2.0 the assertion fails. If I revert django-model-utils back to 3.1.2 it works again.

If I print the value after the assignment under 3.2.0, I get a result of True, and a type of bool.

## Environment

- Django Model Utils version: 3.2.0
- Django version: 2.2.4
- Python version: 3.7.2

**Comment by brianmay** [comment]
On re-reading #382, this looks suspiciously like a match. Closing this for now.

**Comment by brianmay** [comment]
For reference, this model is based on `AbstractBaseUser`, something I didn't include above:

```
class Person(AbstractBaseUser):
    is_active = models.BooleanField(default=True)
    ...
    _tracker = FieldTracker()
```

**Comment by dmugtasimov** [comment]
See: https://github.com/jazzband/django-model-utils/issues/331#issuecomment-739536693
