### ISSUE TITLE
Django 3.0 support

### ISSUE THREAD

**Issue by domdinicola** [jazzband/django-model-utils#400]
Add support for Django 3.0

good that python 2.x support has been already dropped https://github.com/jazzband/django-model-utils/issues/393

**Comment by spielmannj** [comment]
One thing of note is that this means that the `django.utils.six` module was dropped.

**Comment by ephes** [comment]
Just using the master instead of the package worked for me:

git+git://github.com/jazzband/django-model-utils.git#egg=django-model-utils

**Comment by domdinicola** [comment]
@ephes I would rater wait for a package release

**Comment by ephes** [comment]
> @ephes I would rater wait for a package release

Yes, for important projects I would also wait. But I tried this for a small private project and was surprised how many packages break on django 3 because those old python 2 stuff.

**Comment by domdinicola** [comment]
it's cause python 2 is still supported until the end of the year.. people were mostly busy upgrading to py3 (using six)

**Comment by bixbyr** [comment]
I guess other people already discovered that the package is broken in django 3.0. 

Is there a timeline for releasing the next version? I'd like to stick to using a package instead of just pulling from master :(

**Comment by Natim** [comment]
I just found out that master was already supporting Django 3.0 but I am also interested in a release of this current version even if there are works on the way to remove six (#395)

**Comment by Natim** [comment]
#395 has just been merged.

@auvipy can we make a release or do you see any mandatory work to be made first?

**Comment by smithdc1** [comment]
@hramezani are you able to push a release? Seems a shame to have so many commits on master since the last release?

**Comment by hramezani** [comment]
@smithdc1 No. Maybe @jezdez can help.

**Comment by smithdc1** [comment]
According to https://jazzband.co/projects/django-model-utils @charettes (:wave: ) is a project lead?

**Comment by jezdez** [comment]
Yeah, let's prepare a release and wait if @charettes responds first.

**Comment by charettes** [comment]
Should be released in a few hours :)

**Comment by charettes** [comment]
Should be released now https://pypi.org/project/django-model-utils/. Thanks to everyone involve and sorry for the delay here.
