### ISSUE TITLE
StatusModel missing get_status_display() method

### ISSUE THREAD

**Issue by samkuehn** [jazzband/django-model-utils#41]
I assumed that the StatusModel (and perhaps StatusField) would behave like a standard choices field and I would be able to call get_status_display() to get the "human readable" status. 

https://docs.djangoproject.com/en/dev/ref/models/instances/#django.db.models.Model.get_FOO_display

This does not work.  How do you get the "human readable" status?

**Comment by vbabiy** [comment]
Looks like this might be broken in 1.9

**Comment by vbabiy** [comment]
Fixed in #192
