### ISSUE TITLE
Need for a new stable mini release

### ISSUE THREAD

**Issue by bugraaydin** [jazzband/django-model-utils#431]
## Problem

Can we have a new stable release for this as it has been a while since this was last updated and codebase i am working on requires changes from the last commits (the one that adds modified into update_fields of save especially). We don't want to have to use commit version rather than a stable release.

Thank you.

**Comment by bugraaydin** [comment]
@auvipy @Natim

**Comment by smithdc1** [comment]
@bugraaydin there was a new release today. So hopefully that fixes your issue. :-)

**Comment by bugraaydin** [comment]
@smithdc1 thank you for the update, apreciated :)
