### ISSUE TITLE
Prefetc_related on a field with tracker fails

### ISSUE THREAD

**Issue by mahsa-lotfi92** [jazzband/django-model-utils#433]
## Problem

Running prefetch_related on a column which has a tracker will be failed with this error:

`ValueError: "prefetch_related_field_name" does not resolve to an item that supports prefetching - this is an invalid parameter to prefetch_related().`

## Environment

- Django Model Utils version: 4.0.0
- Django version: 2.2
- Python version: 3.8
- Other libraries used, if any: nothing.

## Code examples

Given this code in models.py
```python3
from django.db import models
from model_utils import FieldTracker
class A(models.Model):
    name = models.CharField(max_length=10)


class B(models.Model):
    name = models.CharField(max_length=10)


class C(models.Model):
    a = models.ForeignKey(A, on_delete=models.CASCADE)
    b = models.ForeignKey(B, on_delete=models.CASCADE)
    tracker = FieldTracker(fields=('b',))
```

This is the test case to reproduce the error:
```python3
from django.test import TestCase
from models import *


class TestTracker(TestCase):
    def test_tracker(self):
        a = A.objects.create(name='something')
        b = B.objects.create(name='something')
        C.objects.create(a=a, b=b)
        print(A.objects.prefetch_related('c_set__b').all())
```
and this is the error:
```
ValueError: 'c_set__b' does not resolve to an item that supports prefetching - this is an invalid parameter to prefetch_related().
```
I debugged and found that when running the executing prefetch in Django, rel_obj_descriptor is `tracker.DescriptorWrapper` instead of `ForwardManyToOneDescriptor` which does not have the mehtod `get_prefetch_queryset`

**Comment by IBestuzhev** [comment]
As a workaround, I managed to have Tracker + Prefetch working together by adding this lines:

```python
C.b.get_prefetch_queryset = C.b.descriptor.get_prefetch_queryset
C.b.is_cached = C.b.descriptor.is_cached
```

But I guess the correct fix is to alter [`DescriptorWrapper`](https://github.com/jazzband/django-model-utils/blob/master/model_utils/tracker.py#L63). It should include something like

```python
class DescriptorWrapper:
    # ...
    def __getattr__(self, attr):
        return getattr(self.descriptor, attr)
```
