### ISSUE TITLE
Automatically adding status_changed on StatusModel's save should handle update_fields=None (or set, etc, anything other than list) similar to TimeStampedModel

### ISSUE THREAD

**Issue by bugraaydin** [jazzband/django-model-utils#464]
## Problem

This would raise error in the case where update_fields is provided as None (or set etc, anything other than list)
I completely missed this case for `TimeStampedModel` but some PR have fixed it, i thought it was addressing the `StatusModel` as well, needs to be fixed following a similar manner

**Comment by bugraaydin** [comment]
@hramezani i am closing this one as it is being fixed by PR for another issue
#465

**Comment by hramezani** [comment]
Thanks @bugraaydin
