### ISSUE TITLE
Inheriting model from TimeStampModel and StatusModel results in TypeError

### ISSUE THREAD

**Issue by LHolst** [jazzband/django-model-utils#465]
## Problem
Inheriting custom model class from TimeStampModel and StatusModel results in TypeError

StatusModel.save updates the 'update_fields` kwargs like
```
kwargs['update_fields'] += ['status_changed']
```

maybe related to https://github.com/jazzband/django-model-utils/issues/464
## Environment

- Django Model Utils version: 4.1.0
- Django version: 2.2
- Python version: 3.6
- Other libraries used, if any:

## Code examples

```py
class MyModel(TimeStampModel, StatusModel):
    .....


#later calling 
my_model.save(update_fields=('fieldName',))
 
#results in 
TypeError: unsupported operand type(s) for +=: 'set' and 'list'
```

**Comment by LHolst** [comment]
should StatusModel.save convert the `kwargs['update_fields']` too ?

**Comment by bugraaydin** [comment]
Hello @LHolst, yes exactly, a similar fix was present in `TimeStampedModel`. I forgot to cover that case and thought the actual fix handled `StatusModel` as well, do you have capacity to implement a similar manner like the `TimeStampedModel`'s implementation

**Comment by hramezani** [comment]
This problem introduced in https://github.com/jazzband/django-model-utils/pull/446 because we save a `set` in `kwargs['update_fields']` at `TimeStampedModel.save`  that is inconsistent with `StatusModel.save`(it saves list).

I created a [PR](https://github.com/jazzband/django-model-utils/pull/466) and changed both save method to save `list` in `kwargs['update_fields']`

**Comment by bugraaydin** [comment]
@hramezani sorry about me introducing this problem, i have noticed this missing functionality in our codebase and wanted to contribute back after implementing it for my code as well; was first months of my software engineering experience and implementation was not covering all the possible cases.

**Comment by hramezani** [comment]
@bugraaydin Actually the changes that we made in https://github.com/jazzband/django-model-utils/pull/446 cause the problem I think

**Comment by bugraaydin** [comment]
> @bugraaydin Actually the changes that we made in #446 cause the problem I think

I have introduced the problematic code in #412 and #441, the PR you have linked was an attempt to fix it I suppose but it introduces another problem, inconsistency between kwargs types if the model is using both classes
