### ISSUE TITLE
TimeStampedModel does not work with python 3.8.6, but does with 3.7.9

### ISSUE THREAD

**Issue by LABranagan** [jazzband/django-model-utils#471]
## Problem

Trying to deploy an updated project to Heroku where I had added a model "class Vehicle(TimeStampedModel):" with several entries (including markdownx and autoslugfield).  Earlier in code, I use "from model_utils.models import TimeStampedModel" and have django-model-utils, version 4.1.1 in the requirements,doc.  Heroku deployment responded that "module:  model_utils could not be found".

When I changed the runtime file from "python 3.8.6" to "python 3.7.9" the deployment worked correctly.

## Environment

- Django Model Utils version: 4.1.1
- Django version: 3.1.4
- Python version: 3.8.6 (3.7.9 did work)
- Other libraries used, if any:  
asgiref==3.3.1
beautifulsoup4==4.9.3
dj-database-url==0.5.0
Django==3.1.4
django-autoslug==1.9.8
django-bootstrap4==2.3.1
django-crispy-forms==1.10.0
django-environ==0.4.5
django-heroku==0.3.1
django-markdownx==3.0.1
django-model-utils==4.1.1
django-tables2==2.3.3
gunicorn==20.0.4
Markdown==3.3.3
Pillow==8.0.1
psycopg2==2.8.6
pytz==2020.4
soupsieve==2.1
sqlparse==0.4.1
whitenoise==5.2.0

## Code examples
class Vehicle(TimeStampedModel):  # Does not work with python 3.8.6 but with 3.7.9
    # class Vehicle(models.Model):
    title = models.CharField("Vehicle", max_length=255)  # Title
    slug = AutoSlugField("Vehicle Address", unique=True,
                         always_update=False, populate_from="title")
    engine = models.CharField("Engine", max_length=255, default="none")
    engine_oil = models.CharField("Engine Oil", max_length=30, default="0W")
    mileage = models.IntegerField("Mileage", default=0)
    mileage_update = models.DateField("Mileage updated", default=datetime.now)
    transmission = models.CharField("Trans", max_length=255, default="none")
    transmission_oil = models.CharField("Trans Oil", max_length=20, default="none")
    tires = models.CharField("Tires", max_length=255, default="none")
    oil_filter = models.CharField("Filter", max_length=255, default="none")
    oil_filter_size = models.CharField("Filter Size", max_length=20, default="none")
    oil_reservoir_plug = models.CharField("Reservoir Plug", max_length=20, default="none")
    coolant = models.CharField("Coolant", max_length=30, default='none')
    description = MarkdownxField()  # Definition
    start_date = models.DateField(default=datetime.now)
    last_update = models.DateField(default=datetime.now)

    class Meta:
        verbose_name_plural = "Vehicles"

    @property
    def formatted_markdown(self):  # <--- We'll need this for views.py later
        return "Title: " + self.title + \
               "Description:" + markdownify(self.description)

    def __unicode__(self):
        return self.title
Give code example that demonstrates the issue, or even better, write new tests that fails because of that issue.

Thank you for any feedback.  -- Lyle

**Comment by hramezani** [comment]
I tried your example model with `Python 3.8.6` and it worked on my machine.
Also, we have `Python 3.8` in our Github Actions:
https://github.com/jazzband/django-model-utils/blob/46bf236be20fda0339fa7d138a086439e69f7c81/.github/workflows/test.yml#L12
It means we run all tests against `Python 3.8`.

Could you please provide more information.

**Comment by LABranagan** [comment]
Mr. Hramezani - thank you for investigating my concern.  I also had been able to run my code on my local machine under PyCharm using python 3.9.0, so I was surprised by the error associated with pushing my code to Heroku.  Looking at Change History, I see that there was a bug fix to TimeStampedModel in version 4.1.1.  In response to your test, I retried changing the Heroku runtime.txt to 3.8.6.  This time with success.  Looking back at the build logs, I may have had a old cache of the requirements files that was the source of the error.  Again, thank you for responding and confirming that django-model-utils is compatible.
-- Lyle
