### ISSUE TITLE
Serialization of MultiSelectField within DRF

### ISSUE THREAD

**Issue by asencis** [jazzband/django-model-utils#481]
Hi.

Hoping this is a super simple one - how should we structure the data we send to a MultiSelectField to an API endpoint... is it a csv "string"?

Or do we need our own custom parsers?

**Comment by asencis** [comment]
@jezdez @matthiask @tswicegood @com4 Hi there, sorry to bother again on this ... but does anyone have an idea on this?

**Comment by jezdez** [comment]
This is unrelated to this project, so I'm closing this. Please feel free to ask on the django-users mailing list or #django on Freenode. More info: https://www.djangoproject.com/community/
