### ISSUE TITLE
readthedocs documentation is for an older version

### ISSUE THREAD

**Issue by simonw** [jazzband/django-model-utils#483]
https://django-model-utils.readthedocs.io/en/latest/index.html is currently showing documentation for what looks like version 3.2.0 - but the latest PyPI release at https://pypi.org/project/django-model-utils/ is 4.1.1

<img width="974" alt="django-model-utils_—_django-model-utils_3_2_0_documentation_and_Setup_—_django-model-utils_3_2_0_documentation" src="https://user-images.githubusercontent.com/9599/113942351-80c1ee80-97b5-11eb-8b5f-e60d75316e53.png">

I spotted this because this page https://django-model-utils.readthedocs.io/en/latest/setup.html says "django-model-utils supports Django 1.8 through 2.1 (latest bugfix release in each series only)".

**Comment by hramezani** [comment]
I created https://github.com/jazzband/django-model-utils/pull/484 to fix Django and Python version support in `setup.rst`.
Also, I added changelog to docs.

I don't know why we don't have newer versions on the doc. maybe it is related to publishing the docs.
@jezdez Do you have any idea?

**Comment by jezdez** [comment]
Yeah, django-model-utils was another of the projects that had a broken webhook integration, which I just fixed. This happened to a few Jazzband projects in the past.
I've also just enabled two things:
- [pull request building](https://docs.readthedocs.io/en/latest/pull-requests.html)
- [automatic enabling of versions](https://docs.readthedocs.io/en/latest/automation-rules.html)

**Comment by jezdez** [comment]
(It's taking a bit to build the latest version)

**Comment by jezdez** [comment]
That should be built now, force refresh the page in case the cache sticks.
