### ISSUE TITLE
Undocument breaking changes in FieldTracker in Version 4.1

### ISSUE THREAD

**Issue by MRigal** [jazzband/django-model-utils#491]
## Problem

The Release 4.1, after moving the patch from the `save()` to the `save_base()` method in #404 (@tumb1er FYI) introduced a serioulsy breaking change that was neither announced nor documented (and was obviously not tested brefore). It would have deserved a 5.x update IMHO.

Since the values of the tracker are restored after the call to the `save_base()` method, any check/assumption made on the tracker inside the `save()` Method but **after** the `super().save()` call fails, as the tracker is then "new/empty". This is especially problematic when tracking changes depending on related objects, when working with nested serializers per example.

## Environment

- Django Model Utils version: <4.1 VS 4.1+

## Code examples

```
class MyModel(Model):
        name = models.CharField(max_length=64)
        tracker = FieldTracker()

        def save(self, *args, **kwargs):
            if self.tracker.changed('name'):
                 print("True")
            super().save(*args, **kwargs)
            if self.tracker.changed('name'):
                 print("True")
```
Just calling `MyModel.create()` would result in 2 prints in version <4.1 and in only one in version 4.1+ (the second check will fail as the tracker is resetted on the `save_base()` call inside the `super().save() call)

## Discussion / proposal

@auvipy A work-around is to test before the call to `save()` and then use the variable afterwards for such cases. 

But I honestly find it quite a dramatic regression for the IMHO limited benefit of being able to modify `update_fields` in the `save()` Method.

I would seriously prefer to restore the previous behaviour of patching the `save()` Method, but still add a functionality to support overriding `update_fields`: I would prefer to add a new kwarg `_always_update` to `FieldTracker` where you could define the list of fields that you always want to update. I think also in term of design and readbility it would be a better feature. @tumb1er what do you think about the suggestion? If you validate it, I could draft a PR for this

**Comment by tumb1er** [comment]
Hello @MRigal, thank's for calling.

First, your solution with `_always_update` does not solve problem with dynamic `update_fields` list (i.e. something like "save only changed" scenario).
Second, it's the definition of "changed fields": what is it? I think, changed fields are fields that differ from database version of an object. When you physically save your object to database, changed fields are not changed anymore by this definition.

When working on FieldsTracker, you should also consider abstract parent models, polymorphic models, model mixins and nested `save()` overrides. 

One more argument for `save_base()` is that django signals are raised from that method.

I agree that such breaking changes should be placed to major release, but now we have what we have. Now we can consider two definitions of "changed": that one above and any another. If we don't change the definition, current tracker behavior is correct (but maybe we should add another field set `changed_and_than_saved`, that will not be invalidated at all). If we change definition, complete tracker behavior should be revised.

**Comment by auvipy** [comment]
@hramezani

**Comment by MRigal** [comment]
@tumb1er thanks for replying! As it is sometimes easier to speak around code, I've created a PR with a basic test, that would work on django-model-utils <4.1 and fail on 4.1+, as well as separately, a change proposal to keep the nice work you've added when using `update_fields`.

I think it shows how it is possible to work with a dynamic `update_fields` list. Or maybe you could elaborate on that point.

I agree that what matters is the **definition of changed field**, but this is where I disagree with you. I don't think it should be the exact moment where the `save_base()` returns but in the opposite, the moment where `save()` returns. If "physically" I might agree with you (although it happens technically a little bit before the return, we would already be "late"), from the perspective of the django concepts, I don't, as it is pretty common to continue working on related models inside the `save()` method, after the call to `super().save()`. And at this point in time, I would expect the FieldTracker to not have call `set_saved_fields()` before the **end** of the `save()` Method. And this even more with abstract parent models, polymorphic models, model mixins and nested save() overrides.

I think we might agree that we disagree here, but:
1. IMHO the behavior that has been used for years pre-4.1 should be restored ASAP, @492 being a basis to get a 4.1.2 out of the door with all good additions of the 4.1 series
2. A real definition of the "validity period" of the `FieldTracker` should be agreed on, and precisely documented maybe with insights from previous committers @jezdez @carljm @treyhunner @lucaswiman @st4lk 
3. If it is desirable to switch to your understanding of the FieldTracker, prepare a 5.0 release with documentation about the breaking changes

**Comment by tumb1er** [comment]
@MRigal yes, I disagree with almost all your statements.
1. If we revert behavior ASAP, another person could provide same arguments to revert a revert. 
2. Before "validity period" and "changed definition" are given, nothing should be changed.
3. It will be "stupid" to revert behavior and than revert it again in 5.0. 

Another proposal is to tag 4.1 as 5.0 and bypass step 3 (adding breaking changes to documentation).

And I think there should be third party person as a decision maker.

**Comment by tumb1er** [comment]
@MRigal @gregorgaertner Hello! Review please: https://github.com/jazzband/django-model-utils/pull/494
