### ISSUE TITLE
Enable support for Django 3.2

### ISSUE THREAD

**Issue by kasittig** [jazzband/django-model-utils#493]
The edX project is in the process of upgrading their Django version to 3.2. The project uses django-model-utils which is currently not compatible with Django 3.2. You can find the Github issue associated with this part of the upgrade [here](https://github.com/edx/upgrades/issues/35).

I noticed that PR #482 added support for Django 3.2. Would it be possible for you all to release a new package that includes this change?

Thank you!

**Comment by MRigal** [comment]
@auvipy or @hramezani I've updated the change notes and created a draft here https://github.com/jazzband/django-model-utils/releases (I didn't want to take alone responsibility for the release). You may approve the move and publish the Release Draft. This would also close this issue.

**Comment by hramezani** [comment]
Thanks @MRigal for taking care of the release. I don't have release permission. do you have permission?
