### ISSUE TITLE
Undeclared runtime dependency on setuptools/pkg-resources

### ISSUE THREAD

**Issue by edwardpeek-crown** [jazzband/django-model-utils#506]
## Problem

Importing `model_utils` in a python environment that does not have `setuptools` installed fails with error:
```log
  ...
  File "REDACTED/venv/lib/python3.9/site-packages/model_utils/__init__.py", line 1, in <module>
    from pkg_resources import DistributionNotFound, get_distribution
ModuleNotFoundError: No module named 'pkg_resources'
```
but `setuptools` is not listed under `install_requires` in `setup.py`.

This can occur when using the pip options `--prefix`, `--root`, `--target` to use different python environments between install/runtime.

## Environment

- Django Model Utils version: 4.1.1 / HEAD
- Django version: 3.2.4
- Python version: 3.9
- Other libraries used, if any: setuptools absent

## Code examples

N/A

**Comment by foarsitter** [comment]
https://github.com/jazzband/django-model-utils/pull/545 replaced pg_resources with importlib
