### ISSUE TITLE
django-model-utils support for Django 4

### ISSUE THREAD

**Issue by joegrego** [jazzband/django-model-utils#546]
Hello.

My apologies if I put this in the wrong place.

I work at the University of Michigan's Advanced Genomics Core Lab.  We use django-model-utils in our self-developed sample tracking system. I see it hasn't had a release since late 2021, and I'm wondering if a release is planned, or if we should just pull from master to get support for Django 4?

Thanks,
-Joe Gregoria

**Comment by hugovk** [comment]
I've transferred this from https://github.com/jazzband/help to the project repo: https://github.com/jazzband/django-model-utils

And let's ping the one of [project leads](https://jazzband.co/projects/django-model-utils): @charettes might know.

**Comment by joegrego** [comment]
Thank you @charettes! We appreciate your efforts at the genomics core.
