### ISSUE TITLE
`py.typed` file not include in wheel

### ISSUE THREAD

**Issue by patrick91** [jazzband/django-model-utils#586]
I'm getting a warning from pyright about the type stubs being missing from this project, and by looking at the repo it seems that the `py.typed` file is present and also referenced in the `setup.py`: https://github.com/jazzband/django-model-utils/blob/master/setup.py#L58

but looks it is not included in the wheel:

![CleanShot 2024-01-03 at 11 59 40@2x](https://github.com/jazzband/django-model-utils/assets/667029/92843ce5-5ee3-44c9-85b4-5fb1a7a4752c)

From looking online it seems that the `setup.py` configuration is correct, so not sure why this isn't being included 🤔

**Comment by patrick91** [comment]
maybe it needs to be added in the Manifest too? https://github.com/jazzband/django-model-utils/blob/master/MANIFEST.in

**Comment by foarsitter** [comment]
@patrick91 seems like you pull request is released two weeks ago with v4.4.0. Can you confirm that the release contains the py.typed file?

**Comment by patrick91** [comment]
@foarsitter yup! 

![CleanShot 2024-02-23 at 11 14 11@2x](https://github.com/jazzband/django-model-utils/assets/667029/5ca08a5f-fd4d-40f8-aa8a-68e62c6257d7)
