### ISSUE TITLE
CHANGES is missing entries for 4.5.0 and 4.5.1

### ISSUE THREAD

**Issue by charettes** [jazzband/django-model-utils#619]
## Problem

https://github.com/jazzband/django-model-utils/blob/master/CHANGES.rst

I think it should be updated before we release any new versions.

cc @foarsitter

**Comment by foarsitter** [comment]
Ah yes, you are right. Pushed them to my release branch but they should merged into main: https://github.com/jazzband/django-model-utils/commit/53cebc57c31aed14ec59cebf8ef644dc82a9020c

By any change, can you cherrypick this commit? 

@mthuurne can you notify @charettes by email of your change?

**Comment by foarsitter** [comment]
I pushed the correct change-log, sorry for the inconvenience.

**Comment by charettes** [comment]
Thanks to both of you 🙇
